# Generated by Django 2.1.5 on 2019-02-11 09:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_or_credit', models.BooleanField(default=False)),
                ('ammount', models.FloatField(default=0.0)),
                ('remarks', models.CharField(default=None, max_length=90)),
                ('transaction_time', models.DateTimeField(default=datetime.datetime.now)),
                ('transaction_type', models.CharField(choices=[('tu', 'TopUp'), ('gf', 'Game Fee'), ('wd', 'Withdrawal')], max_length=2, null=True)),
                ('account_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
