# Generated by Django 2.1.5 on 2019-02-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190211_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='ammount',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='debit_or_credit',
        ),
        migrations.RemoveField(
            model_name='account',
            name='transaction_time',
        ),
        migrations.RemoveField(
            model_name='account',
            name='transaction_type',
        ),
    ]
