# Generated by Django 2.1.5 on 2019-02-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('reg_before', models.DateTimeField(null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
