# Generated by Django 2.1.5 on 2019-02-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20190210_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='game',
        ),
    ]
