# Generated by Django 2.1.5 on 2019-02-11 18:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_or_credit', models.CharField(choices=[('d', 'Debit'), ('c', 'Credit')], max_length=1, null=True)),
                ('ammount', models.FloatField(default=0.0)),
                ('transaction_type', models.CharField(choices=[('tu', 'TopUp'), ('gf', 'Game Fee'), ('wd', 'Withdrawal'), ('tr', 'transfer')], max_length=2, null=True)),
                ('transaction_time', models.DateTimeField(default=datetime.datetime.now)),
                ('remarks', models.CharField(default=None, max_length=90)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Account_holder', to=settings.AUTH_USER_MODEL)),
                ('counterparty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_involved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
