# Generated by Django 2.1.5 on 2019-02-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20190214_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='debit_or_credit',
        ),
    ]
