# Generated by Django 2.1.5 on 2019-02-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0002_auto_20190209_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, null=True)),
                ('genre', models.CharField(choices=[('ac', 'Action'), ('sh', 'Shooter'), ('st', 'Strategy'), ('rc', 'Race'), ('o', 'Other'), ('sp', 'Sports')], max_length=1, null=True)),
                ('description', models.TextField(max_length=100, null=True)),
                ('game', models.ManyToManyField(to='userprofile.UserProfile')),
            ],
        ),
    ]
