# Generated by Django 2.1.5 on 2019-02-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game',
            new_name='player',
        ),
    ]
