# Generated by Django 2.1.5 on 2019-02-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190210_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('ac', 'Action'), ('sh', 'Shooter'), ('st', 'Strategy'), ('rc', 'Race'), ('o', 'Other'), ('sp', 'Sports')], max_length=10, null=True),
        ),
    ]
