# Generated by Django 2.1.5 on 2019-02-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190210_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.ManyToManyField(null=True, to='userprofile.UserProfile'),
        ),
    ]
