# Generated by Django 2.1.5 on 2019-02-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_game_player'),
        ('userprofile', '0002_auto_20190209_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='player_games',
            field=models.ManyToManyField(null=True, to='game.Game'),
        ),
    ]
