# Generated by Django 2.1.5 on 2019-02-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_player_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='player_games',
            field=models.ManyToManyField(null=True, related_name='games', to='game.Game'),
        ),
    ]
